Inference using PINTS
pkpdapp-team/pkpdapp pull request #242
Opened 2021-12-21 16:36 UTC by ben18785

Currently:

- fixes noise parameters at user-specified values
- uses the default parameter values for the optimiser or sampler starting values
- is untested for multiple output inference problems (this was because I was unable to figure out whether I could use one of the multiple output pk models in this way). Note the Myokit forward model wrapping _is_ tested -- just the PINTS inference is not
- creates an `InferenceFunctionResults` model that captures function evaluations for each iteration for each chain

2021-12-21 17:07 UTC, ben18785 commented
Closing as thing runners have hung due to this line `run_inference.delay(new_inference.id)`.

2021-12-23 09:40 UTC, martinjrobins requested changes
this is great, thanks @ben18785. I've noted a few changes, and I'll try to deal with these myself today

2021-12-23 09:40 UTC, martinjrobins commented on pkpdapp/pkpdapp/tests/test_models/test_inference_mixin.py
> +        self.assertTrue(abs(val - -113.33099855566624) < 0.1)
use https://docs.python.org/3/library/unittest.html#unittest.TestCase.assertAlmostEqual

2021-12-23 09:40 UTC, martinjrobins commented on pkpdapp/pkpdapp/tests/test_models/test_inference_mixin.py
> +        self.assertTrue(abs(val - -113.33099855566624) < 0.1)
and below

2021-12-23 10:40 UTC, martinjrobins commented on pkpdapp/pkpdapp/models/myokit_pints_forward_model.py
> +    def __init__(self, myokit_model, myokit_simulator, outputs=None,
actually you can't!

2021-12-23 11:38 UTC, martinjrobins approved these changes
happy to merge now

2021-12-23 11:44 UTC, merged