refactor: allow for multiple Myokit simulations
pkpdapp-team/pkpdapp pull request #366
Opened 2024-03-12 16:00 UTC by eatyourgreens

Refactor the Myokit model mixin to allow multiple simulations to be run. Each simulation has its own dosing protocol and dosing events.

2024-03-12 17:00 UTC, martinjrobins requested changes
hi @eatyourgreens, this mostly looks right, but the number of simulations is not quite right:

You should perform 1 simulation for each distinct subject group. Each group of subjects will have 1 or more protocols associated with them (each dosing into a different variable). For each of those groups you want to gather the protocols for that group then run a simulation using all of the protocols for that group (you wont get an error since they will all be dosing into separate variables)

2024-03-13 17:08 UTC, eatyourgreens commented on pkpdapp/pkpdapp/models/myokit_model_mixin.py
> +            subject_protocols = [
I rewrote this so it's now expecting a list of subjects for each model, then getting the protocols from that list of subjects. My test groups only have one protocol per subject group, but it should work with more than one protocol.

2024-03-13 17:12 UTC, eatyourgreens commented on pkpdapp/pkpdapp/models/myokit_model_mixin.py
> +            print(self.serialize_datalog(sim.run(time_max, log=outputs), model))
All done now. THe API is sending back lists of simulations. Tests are updated, and the API schema. The Simulations tab simply loops through the response and generates a plot for each item. I'll work on the frontend in a separate PR. I think the Python changes are ready to go now (except for properly adding subject groups to the models.)

2024-03-15 10:53 UTC, eatyourgreens commented on pkpdapp/pkpdapp/models/myokit_model_mixin.py
> +        ]
Now that subject groups are in the app, this should ignore protocols and return the groups linked to this dataset's subjects

2024-03-15 17:36 UTC, merged