draft for Issue 54 models
pkpdapp-team/pkpdapp pull request #56
Opened 2020-12-03 09:50 UTC by martinjrobins

An initial draft for #54. I think we'll have to work on the schema a bit, I just added the fields that were in the issue. But just to get it started

2020-12-03 16:52 UTC, DavAug requested changes
Thanks @martinjrobins I think that looks really good!

I just have a couple minor comments on the documentation. 

So are we going to write tests for each migration now? Or are we just writing a test that checks that the after the migrations are performed the database is set up the way we would like it to be.

2020-12-03 16:52 UTC, DavAug commented on pkpdapp/pkpdapp/models/biomarker_type.py
> +    A biomarker type. Eache value, or biomarker, in a dataset must be one of
Same here.

2020-12-04 06:24 UTC, martinjrobins commented on pkpdapp/pkpdapp/models/biomarker.py
> +    A biomarker measurement value for use in a dataset
yea, good point. I didn't write these cause I couldn't find the documentation on how to write docstrings for django, but now I have (https://docs.djangoproject.com/en/3.1/ref/contrib/admin/admindocs/). Looks like you put help strings for each field in the `help_text` attribute. I'll do that now

2020-12-04 06:27 UTC, martinjrobins commented
> So are we going to write tests for each migration now? Or are we just writing a test that checks that the after the migrations are performed the database is set up the way we would like it to be.

I think we want to aim for testing at least the vast majority of all code, which includes the migrations. Note that I only wrote an explicit test for unapplying the 2nd migration, as this is otherwise not covered (as codecov told me :) ). I don't think we need to explicitly test applying the 1st and 2nd migration, as the tests of the models itself cover these (i.e. if the migrations failed, then the model tests will also fail).

2021-01-08 14:31 UTC, DavAug approved these changes
Thanks @martinjrobins . Quite cool that Django constructs the documentation automatically!

2021-01-08 16:09 UTC, ben18785 commented
@martinjrobins Do we need both this PR and #59? It looks like this one creates models which #59 also does...

2021-01-08 16:42 UTC, martinjrobins commented
> @martinjrobins Do we need both this PR and #59? It looks like this one creates models which #59 also does...

This PR branch is branched from the #59 PR, as they follow on from each other. But they address different issues, so I kept them separate.

2021-01-08 16:44 UTC, ben18785 commented
@martinjrobins Ok, thanks -- sorry for duncing!

2021-01-11 10:02 UTC, merged